### ISSUE TITLE
Link error on Windows (undefined reference to `__errno')

### ISSUE THREAD

**Issue by andy128k** [alexcrichton/backtrace-rs#190]
There is an link error (``undefined reference to `__errno'``) in my application after update of `backtrace` from 0.3.15 to 0.3.26.

[Here](https://github.com/andy128k/PassStorage/pull/112) I bisected to [this commit](https://github.com/alexcrichton/backtrace-rs/commit/eca718ca95ab08411eea4e899e41cdfd3daf79d3).

This issue affects Windows (on AppVeyor) only.

**Comment by alexcrichton** [comment]
Thanks for the report! I think though that this is a compiler mismatch between what compiled the C code in libbacktrace and what is linking the code at the end. It looks like you're downloading custom MinGW compilers, and maybe something needs to be updated in one location or another? I don't think this is a bug with the code, however, so I'm going to close.
