### ISSUE TITLE
backtrace 0.3.11 fails to compile on Rust versions < 1.30.0.  backtrace 0.3.10 did.

### ISSUE THREAD

**Issue by paul-tcell** [alexcrichton/backtrace-rs#136]
here's the errors with rust 1.29.2:
```
error[E0308]: mismatched types
   --> /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:156:60
    |
156 |         STATE = bt::backtrace_create_state(ptr::null(), 0, error_cb,
    |                                                            ^^^^^^^^ expected enum `std::os::raw::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut std::os::raw::c_void, *const i8, i32)`
               found type `extern "C" fn(*mut libc::c_void, *const i8, i32) {symbolize::libbacktrace::error_cb}`

   Compiling phf_generator v0.7.23
error[E0308]: mismatched types
   --> /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:172:36
    |
172 |                                    pcinfo_cb, error_cb,
    |                                    ^^^^^^^^^ expected enum `std::os::raw::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut std::os::raw::c_void, usize, *const i8, i32, *const i8) -> i32`
               found type `extern "C" fn(*mut libc::c_void, usize, *const i8, i32, *const i8) -> i32 {symbolize::libbacktrace::pcinfo_cb}`

error[E0308]: mismatched types
   --> /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:172:47
    |
172 |                                    pcinfo_cb, error_cb,
    |                                               ^^^^^^^^ expected enum `std::os::raw::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut std::os::raw::c_void, *const i8, i32)`
               found type `extern "C" fn(*mut libc::c_void, *const i8, i32) {symbolize::libbacktrace::error_cb}`

   Compiling uuid v0.7.1
error[E0308]: mismatched types
   --> /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:176:31
    |
176 |                               syminfo_cb, error_cb,
    |                               ^^^^^^^^^^ expected enum `std::os::raw::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut std::os::raw::c_void, usize, *const i8, usize, usize)`
               found type `extern "C" fn(*mut libc::c_void, usize, *const i8, usize, usize) {symbolize::libbacktrace::syminfo_cb}`

error[E0308]: mismatched types
   --> /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:176:43
    |
176 |                               syminfo_cb, error_cb,
    |                                           ^^^^^^^^ expected enum `std::os::raw::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut std::os::raw::c_void, *const i8, i32)`
               found type `extern "C" fn(*mut libc::c_void, *const i8, i32) {symbolize::libbacktrace::error_cb}`

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0308`.
```

**Comment by alexcrichton** [comment]
Ah ok, makes sense with Rust 1.29! I personally try to support the latest stable and previous stable, but further back I don't do so myself but am willing to review PRs for!

**Comment by nacardin** [comment]
0.3.11 is also failing to compile on stable 1.31.0

```
Compiling backtrace v0.3.11
error[E0308]: mismatched types
   --> /home/nacardin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:156:60
    |
156 |         STATE = bt::backtrace_create_state(ptr::null(), 0, error_cb,
    |                                                            ^^^^^^^^ expected enum `core::ffi::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut core::ffi::c_void, *const i8, i32)`
               found type `extern "C" fn(*mut libc::c_void, *const i8, i32) {symbolize::libbacktrace::error_cb}`
```

**Comment by alexcrichton** [comment]
@nacardin where did you get the 1.31.0 compiler from? Tha's working locally for me with the 1.31.0 compiler

**Comment by ccakes** [comment]
I'm getting the same errors on 1.31.0 under CentOS 7 built using [this Dockerfile](https://gist.github.com/ccakes/101b23ab2a2f655cf5bd296da7e97753). Hope a bit more info helps

```
[root@8650b8634778 app]# rustup show
Default host: x86_64-unknown-linux-gnu

stable-x86_64-unknown-linux-gnu (default)
rustc 1.31.0 (abe02cefd 2018-12-04)
```

<details>
  <summary>Click for build log</summary>

```
[root@8650b8634778 app]# cargo build --release --target=x86_64-unknown-linux-gnu
   Compiling backtrace v0.3.11
   Compiling synstructure v0.10.1
error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:156:60
    |
156 |         STATE = bt::backtrace_create_state(ptr::null(), 0, error_cb,
    |                                                            ^^^^^^^^ expected enum `core::ffi::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut core::ffi::c_void, *const i8, i32)`
               found type `extern "C" fn(*mut libc::c_void, *const i8, i32) {symbolize::libbacktrace::error_cb}`

error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:172:36
    |
172 |                                    pcinfo_cb, error_cb,
    |                                    ^^^^^^^^^ expected enum `core::ffi::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut core::ffi::c_void, usize, *const i8, i32, *const i8) -> i32`
               found type `extern "C" fn(*mut libc::c_void, usize, *const i8, i32, *const i8) -> i32 {symbolize::libbacktrace::pcinfo_cb}`

error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:172:47
    |
172 |                                    pcinfo_cb, error_cb,
    |                                               ^^^^^^^^ expected enum `core::ffi::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut core::ffi::c_void, *const i8, i32)`
               found type `extern "C" fn(*mut libc::c_void, *const i8, i32) {symbolize::libbacktrace::error_cb}`

error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:176:31
    |
176 |                               syminfo_cb, error_cb,
    |                               ^^^^^^^^^^ expected enum `core::ffi::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut core::ffi::c_void, usize, *const i8, usize, usize)`
               found type `extern "C" fn(*mut libc::c_void, usize, *const i8, usize, usize) {symbolize::libbacktrace::syminfo_cb}`

error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:176:43
    |
176 |                               syminfo_cb, error_cb,
    |                                           ^^^^^^^^ expected enum `core::ffi::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut core::ffi::c_void, *const i8, i32)`
               found type `extern "C" fn(*mut libc::c_void, *const i8, i32) {symbolize::libbacktrace::error_cb}`

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `backtrace`.
warning: build failed, waiting for other jobs to finish...
error: build failed
[root@8650b8634778 app]#
```

</details>

**Comment by vlisivka** [comment]
Same problem:

Rust (latest version via rustup):
```
stable-x86_64-unknown-linux-gnu (default)
rustc 1.31.0 (abe02cefd 2018-12-04)
```
Target: `armv7-unknown-linux-gnueabihf`, `x86_64-unknown-linux-gnu`

OS: Fedora 28

``` build log
   Compiling backtrace v0.3.11                                                                                                                    
error[E0308]: mismatched types                                                                                                                    
   --> /home/vlisivka/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:156:60                       
    |                                                                                                                                             
156 |         STATE = bt::backtrace_create_state(ptr::null(), 0, error_cb,                                                                        
    |                                                            ^^^^^^^^ expected enum `core::ffi::c_void`, found enum `libc::c_void`            
    |                                                                                                                                             
    = note: expected type `extern "C" fn(*mut core::ffi::c_void, *const u8, i32)`                                                                 
               found type `extern "C" fn(*mut libc::c_void, *const u8, i32) {symbolize::libbacktrace::error_cb}`                                  
                                                                                                                                                  
error[E0308]: mismatched types                                                                                                                    
   --> /home/vlisivka/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:172:36                       
    |                                                                                                                                             
172 |                                    pcinfo_cb, error_cb,                                                                                     
    |                                    ^^^^^^^^^ expected enum `core::ffi::c_void`, found enum `libc::c_void`                                   
    |                                                                                                                                             
    = note: expected type `extern "C" fn(*mut core::ffi::c_void, usize, *const u8, i32, *const u8) -> i32`                                        
               found type `extern "C" fn(*mut libc::c_void, usize, *const u8, i32, *const u8) -> i32 {symbolize::libbacktrace::pcinfo_cb}`        
                                                                                                                                                  
error[E0308]: mismatched types                                                                                                                    
   --> /home/vlisivka/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:172:47                       
    |                                                                                                                                             
172 |                                    pcinfo_cb, error_cb,                                                                                     
    |                                               ^^^^^^^^ expected enum `core::ffi::c_void`, found enum `libc::c_void`                         
    |                                                                                                                                             
    = note: expected type `extern "C" fn(*mut core::ffi::c_void, *const u8, i32)`                                                                 
               found type `extern "C" fn(*mut libc::c_void, *const u8, i32) {symbolize::libbacktrace::error_cb}`                                  
                                                                                                                                                  
error[E0308]: mismatched types                                                                                                                    
   --> /home/vlisivka/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:176:31                       
    |                                                                                                                                             
176 |                               syminfo_cb, error_cb,                                                                                         
    |                               ^^^^^^^^^^ expected enum `core::ffi::c_void`, found enum `libc::c_void`                                       
    |                                                                                                                                             
    = note: expected type `extern "C" fn(*mut core::ffi::c_void, usize, *const u8, usize, usize)`                                                 
               found type `extern "C" fn(*mut libc::c_void, usize, *const u8, usize, usize) {symbolize::libbacktrace::syminfo_cb}`                
                                                                                                                                                  
error[E0308]: mismatched types                                                                                                                    
   --> /home/vlisivka/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.11/src/symbolize/libbacktrace.rs:176:43                       
    |                                                                                                                                             
176 |                               syminfo_cb, error_cb,                                                                                         
    |                                           ^^^^^^^^ expected enum `core::ffi::c_void`, found enum `libc::c_void`                             
    |                                                                                                                                             
    = note: expected type `extern "C" fn(*mut core::ffi::c_void, *const u8, i32)`                                                                 
               found type `extern "C" fn(*mut libc::c_void, *const u8, i32) {symbolize::libbacktrace::error_cb}`                                  
                                                                                                                                                  
error: aborting due to 5 previous errors                                                                                                          
                                                                                                                                                  
For more information about this error, try `rustc --explain E0308`.                                                                               
error: Could not compile `backtrace`.                                                                                                             

```

**Comment by silwol** [comment]
Is it possible that this happens when not using the latest version of the libc crate? It sounds to me as if this would happen with libc crate versions before https://github.com/rust-lang/libc/issues/180 got merged.

**Comment by vlisivka** [comment]
Yes, command `cargo update -p libc --precise 0.2.45` fixes the problem.

**Comment by alexcrichton** [comment]
Oops a mistake on my part! I've increased the version requirement of `libc` now

**Comment by harishbm34** [comment]
@alexcrichton : Still getting the same error : 

error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.12/src/symbolize/libbacktrace.rs:156:60
    |
156 |         STATE = bt::backtrace_create_state(ptr::null(), 0, error_cb,
    |                                                            ^^^^^^^^ expected enum `std::os::raw::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut std::os::raw::c_void, *const i8, i32)`
               found type `extern "C" fn(*mut libc::c_void, *const i8, i32) {symbolize::libbacktrace::error_cb}`

error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.12/src/symbolize/libbacktrace.rs:172:36
    |
172 |                                    pcinfo_cb, error_cb,
    |                                    ^^^^^^^^^ expected enum `std::os::raw::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut std::os::raw::c_void, usize, *const i8, i32, *const i8) -> i32`
               found type `extern "C" fn(*mut libc::c_void, usize, *const i8, i32, *const i8) -> i32 {symbolize::libbacktrace::pcinfo_cb}`

error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.12/src/symbolize/libbacktrace.rs:172:47
    |
172 |                                    pcinfo_cb, error_cb,
    |                                               ^^^^^^^^ expected enum `std::os::raw::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut std::os::raw::c_void, *const i8, i32)`
               found type `extern "C" fn(*mut libc::c_void, *const i8, i32) {symbolize::libbacktrace::error_cb}`

error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.12/src/symbolize/libbacktrace.rs:176:31
    |
176 |                               syminfo_cb, error_cb,
    |                               ^^^^^^^^^^ expected enum `std::os::raw::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut std::os::raw::c_void, usize, *const i8, usize, usize)`
               found type `extern "C" fn(*mut libc::c_void, usize, *const i8, usize, usize) {symbolize::libbacktrace::syminfo_cb}`

error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.12/src/symbolize/libbacktrace.rs:176:43
    |
176 |                               syminfo_cb, error_cb,
    |                                           ^^^^^^^^ expected enum `std::os::raw::c_void`, found enum `libc::c_void`
    |
    = note: expected type `extern "C" fn(*mut std::os::raw::c_void, *const i8, i32)`
               found type `extern "C" fn(*mut libc::c_void, *const i8, i32) {symbolize::libbacktrace::error_cb}`

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `backtrace`.

Could you please help me to fix this.

**Comment by vlisivka** [comment]
And latest version of rustc is required for latest version of libc.

**Comment by harishbm34** [comment]
I am using latest version of rustc that is 1.31.0  and it’s getting latest version of libc also. But build is failing with the above error.

**Comment by alexcrichton** [comment]
@vlisivka can you post any build errors you're getting? I don't think that's the case

@harishbm34 can you also post build errors you're getting? I'm unable to reproduce locally

**Comment by vlisivka** [comment]
@alexcrichton I already posted my error log. I have nothing to add.

**Comment by paul-tcell** [comment]
builds for me with 1.31.0 on ubuntu and centos 6.   Did you guys do a `cargo update` ?  🙂

**Comment by harishbm34** [comment]
@alexcrichton : I am trying to build on macOS Mojave and the rustc version : 
rustc 1.31.0 (abe02cefd 2018-12-04)

Getting the same mentioned error.

**Comment by alexcrichton** [comment]
Hm well ok, if y'all can give any more info to help reproduce I can help track this down, otherwise with all the info here I can't reproduce or help track it down so this'll go unfixed...

**Comment by harishbm34** [comment]
@alexcrichton : Will you be able to look into my issue which I have posted above.

**Comment by alexcrichton** [comment]
@harishbm34 it unfortunately looks the same as all the others, where I can't reproduce it locally.

**Comment by harishbm34** [comment]
@alexcrichton : In one of the thread, I have mentioned the steps to replicate the error.

**Comment by vitalyd** [comment]
I had a similar problem, but in the context of building `backtrace-rs` from `Bazel` using vendored versions of the crates.  `libc 0.2.45` does indeed solve the issue, but one needs to ensure the `--cfg=core_cvoid` is passed when compiling it.  In my case, this wasn't happening because `libc` has a custom `build.rs` that does this, but that wasn't carried over to our `Bazel` build.

Not sure if this helps, but wanted to mention this in case it does.
